---
# If you're Josh, use the compose file we submitted to Canvas with environment variables pre-set
services:
  spotufy:
    container_name: spotufy
    image: ghcr.io/chunned/spotufy:latest
    ports:
      - 8080:8080
    environment:
      - CLIENT_ID=
      - CLIENT_SECRET=
      - GENIUS_TOKEN=
      - SECRET_KEY=
      - CALLBACK_URL=https://spotufy.chunned.ca/callback

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - spotufy
