---
version: '3.9'
services:
  spotufy:
    image: chunned/spotufy:latest
    environment:
      - CLIENT_ID=<client id>
      - CLIENT_SECRET=<client secret>
      - GENIUS_TOKEN=<genius token>
      - SECRET_KEY=<secret key>
      - CALLBACK_URL=<callback url>
    ports:
      - '9191:9191'