# Credit: https://www.youtube.com/watch?v=f5AlQE0i5m0
name: docker-test
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: chunned/spotufy:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'docker'
      - name: Login
        run: echo ${{ secrets.PAT }} | docker login ghcr.io -u chunned --password-stdin

      - name: Build and Publish
        run: |
          docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  deploy:
    needs: publish
    name: deploy-image
    runs-on: ubuntu-latest
    steps:
      - name: install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && docker compose pull && docker compose up -d && exit"

      - name: cleanup
        run: rm -rf ~/.ssh
